// <auto-generated />
using System;
using HairSalon.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HairSalon.Migrations
{
    [DbContext(typeof(HairSalonContext))]
    [Migration("20231020054745_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HairSalon.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClientName")
                        .HasColumnType("longtext");

                    b.Property<string>("ClientPhone")
                        .HasColumnType("longtext");

                    b.Property<int?>("StylistID")
                        .HasColumnType("int");

                    b.HasKey("ClientID");

                    b.HasIndex("StylistID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("HairSalon.Models.Stylist", b =>
                {
                    b.Property<int>("StylistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("StylistDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("StylistName")
                        .HasColumnType("longtext");

                    b.HasKey("StylistID");

                    b.ToTable("Stylist");
                });

            modelBuilder.Entity("HairSalon.Models.Client", b =>
                {
                    b.HasOne("HairSalon.Models.Stylist", null)
                        .WithMany("StylistClient")
                        .HasForeignKey("StylistID");
                });

            modelBuilder.Entity("HairSalon.Models.Stylist", b =>
                {
                    b.Navigation("StylistClient");
                });
#pragma warning restore 612, 618
        }
    }
}
